### ISSUE TITLE
Error: Missing SITE_URL in env file

### ISSUE THREAD

**Issue by Serbia580** [Mehdi-BHA/awesomefolio#10]
<html>
<body>

Error: Missing SITE_URL in env file
--
03:26:35.377 | at generateRssFeed (/vercel/path0/.next/server/app/blog/page.js:502:15)
03:26:35.377 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
03:26:35.377 | at async getData (/vercel/path0/.next/server/app/blog/page.js:542:5)
03:26:35.377 | at async Blog (/vercel/path0/.next/server/app/blog/page.js:560:29)
03:26:35.403 |  
03:26:35.403 | Error occurred prerendering page "/blog". Read more: https://nextjs.org/docs/messages/prerender-error
03:26:35.403 | Error: Missing SITE_URL in env file
03:26:35.403 | at generateRssFeed (/vercel/path0/.next/server/app/blog/page.js:502:15)
03:26:35.403 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
03:26:35.403 | at async getData (/vercel/path0/.next/server/app/blog/page.js:542:5)
03:26:35.403 | at async Blog (/vercel/path0/.next/server/app/blog/page.js:560:29)

</body>
</html>

**Comment by fhnasgf28** [comment]
help me please 

how to fix this error, first running 

if (!parsedPageId) {
> 240 |   throw new Error(`invalid notion pageId "${pageId}"`)
      |        ^
  241 | }
  242 | 
  243 | const body = {
